# Generated by Django 5.1.2 on 2024-11-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CED', 'Cédula'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CED', 'Cédula'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Seguro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('CE', 'Cédula extranjera')], max_length=3)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('GERENTE', 'Gerente'), ('ADMINISTRADOR', 'Administrador')], max_length=14)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('numero', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima', models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta ')], max_length=20)),
                ('estado', models.BooleanField()),
                ('aseguradora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aseguradora')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
                ('tipo_seguro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza_Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.beneficiario')),
                ('poliza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RESUELTO', 'Resuelto')], max_length=15)),
                ('poliza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_seguro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_seguro')),
            ],
        ),
    ]
