# Generated by Django 5.1.2 on 2024-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='nombre',
        ),
        migrations.AddField(
            model_name='poliza',
            name='num',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
