# Generated by Django 5.1.2 on 2024-11-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_poliza_seguro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='tipo_seguro_id',
        ),
    ]
