# Generated by Django 5.1.2 on 2024-11-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_poliza_seguro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
    ]
