# Generated by Django 5.1.2 on 2024-11-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('CE', 'Cédula de extranjería')], max_length=3),
        ),
    ]
