# Generated by Django 5.1.2 on 2024-11-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
