# Generated by Django 5.1.2 on 2024-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_beneficiario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='num_documento',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Poliza_Beneficiario',
        ),
    ]
