# Generated by Django 5.1.2 on 2024-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_beneficiario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
