# Generated by Django 5.1.2 on 2024-11-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_siniestro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.beneficiario')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poliza')),
            ],
        ),
    ]
