# Generated by Django 5.1.2 on 2024-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_policy_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='prima',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=10),
        ),
    ]
