# Generated by Django 5.1.2 on 2024-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_poliza_prima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadania'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('PA', 'Pasaporte'), ('CE', 'Cédula de extranjería')], max_length=3),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='estado',
            field=models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado'), ('RESUELTO', 'Resuelto')], max_length=15),
        ),
    ]
